### ISSUE TITLE
IPMI ryan partly broken

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#244]
since the bios update, the new IPMI over https is partly broken:

this works: `curl --insecure -H "Host: 172.24.90.7" https://ryan-mgmt.dse.in.tum.de/restgui/start.html`

this returns various internal errors `curl --insecure -H "Host: ryan-mgmt.dse.in.tum.de" https://ryan-mgmt.dse.in.tum.de/restgui/start.html`

this issue has been reproduced by different people on different browsers (@mmisono)

**Comment by mmisono** [comment]
DNS seems correct
```
% dig ryan-mgmt.dse.in.tum.de
[...]
ryan-mgmt.dse.in.tum.de. 86400  IN      A       172.24.90.7
```

**Comment by pogobanane** [comment]
its an issue in the IPMI implementation. It breaks when the HTTP GET request contains a `Host` header that is not an ip address. Maybe we can up/downgrade the idrac/ipmi webinterface to another version.

**Comment by mmisono** [comment]
during BIOS/firmware updates, one update (system management something?) fails and maybe that relates..

**Comment by mmisono** [comment]
This is the update log but it doesn't say what update failed.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/186170/218747793-d4a725f6-db2e-40ee-ae6a-b81610f1d3f5.png">

**Comment by mmisono** [comment]
In racadm, System.ServerOS.HostName is empty, but so is graham.
```
racadm>>get System.ServerOS.HostName
[Key=System.Embedded.1#ServerOS.1]
HostName=
```

**Comment by mmisono** [comment]
It seems we need to configure `iDRAC.WebServer.ManualDNSEntry` in recent firmware. (cf. https://www.dell.com/community/PowerEdge-Hardware-General/5-10-00-00-FQDN-400-Bad-Request/td-p/8105241. graham does not have that configuration probably because the firmware is not up-to-date)

```
racadm>>get idRAC.WebServer.ManualDNSEntry
[Key=idRAC.Embedded.1#WebServer.1]
ManualDNSEntry=
racadm>>set idRAC.WebServer.ManualDNSEntry ryan-mgmt.dse.in.tum.de
[Key=idRAC.Embedded.1#WebServer.1]
Object value modified successfully
```

Now we can access https://ryan-mgmt.dse.in.tum.de/ again.

**Comment by pogobanane** [comment]
does that setting have a GUI entry? Otherwise we should dump the idrac configuration to a file for documentaion/backup purpose.

**Comment by mmisono** [comment]
I think the configuration should be in `iDRAC Settings > Services > Web Server > Settings` since some other settings in `iDRAC.WebServer` are there but actually not. Maybe we need to update the web server as well?

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/186170/219361699-b55937c4-a262-4d91-a2e8-fafee490be08.png">

```
racadm>>get iDRAC.WebServer
[Key=iDRAC.Embedded.1#WebServer.1]
BlockHTTPPort=Disabled
CustomCipherString=
Enable=Enabled
HostHeaderCheck=Enabled
Http2Enable=Disabled
HttpPort=80
HttpsPort=443
HttpsRedirection=Enabled
ManualDNSEntry=ryan-mgmt.dse.in.tum.de
#MaxNumberOfSessions=8
SSLEncryptionBitLength=128-Bit or higher
Timeout=1800
TitleBarOption=Auto
TitleBarOptionCustom=
TLSProtocol=TLS 1.1 and Higher
```
